/**
 * 競輪のYoutubeのユーザーIDを取得する
 * @param placeName
 * @returns YoutubeのライブURL
 */

export const YoutubeUserIdMapForKeirin: Record<string, string> = {
    函館: 'rinrin-hakodate-Keirin',
    青森: 'もりんちゃんねる葵萌輪',
    いわき平: 'iwakitairakeirin',
    弥彦: 'yahiko0256',
    前橋: '前橋競輪場',
    取手: 'torideBank',
    宇都宮: 'UTSUNOMIYA500KEIRIN',
    大宮: 'omiyakeirin',
    西武園: 'seibuenkeirin',
    京王閣: 'tokyokeiokaku',
    立川: '立川ライブ中継',
    松戸: '松戸けいりん',
    千葉: 'pist6shorts430',
    川崎: '川崎競輪場公式',
    平塚: 'shonanbank400',
    小田原: '小田原競輪解説チャンネル',
    伊東: 'itokeirin',
    静岡: 'shizuokakeirin',
    名古屋: '758keirin',
    岐阜: '岐阜けいりん',
    大垣: 'ogakikeirin',
    豊橋: '競輪場豊橋',
    富山: 'toyamakeirin',
    松阪: 'matsusaka_keirin_LIVE',
    四日市: 'keirinyokkaichi104',
    福井: 'fukuikeirin',
    奈良: 'narakeirin',
    向日町: 'tube6082',
    和歌山: 'wakayamakeirin',
    岸和田: 'chalionkun',
    玉野: 'LIVE-zr9mi',
    広島: 'ひろしまけいりんぴーすけチャンネル-n8u',
    防府: '防府けいりん',
    高松: 'takamatsu-keirin',
    小松島: 'ponstarkomatsushima',
    高知: '高知競輪ちゃんねる公式',
    松山: '松山競輪',
    小倉: '小倉競輪公式チャンネル',
    久留米: '久留米けいりんチャンネル公式',
    武雄: '武雄競輪-t9x',
    佐世保: '公式_佐世保競輪',
    別府: 'beppukeirin136',
    熊本: 'kumamotokeirin87',
};
