// Public API surface of @race-schedule/core.
// Only symbols actually consumed by other packages (api/batch/scraping/db) and
// their tests are re-exported here. Internal-only helpers stay module-private.
// See #136.

// constants
export {
    DI_TOKENS,
    YoutubeUserIdMapForJra,
    YoutubeUserIdMapForKeirin,
    YoutubeUserIdMapForNar,
} from './constants';

// domain
export type {
    GoogleCalendarColorDefinition,
    GoogleCalendarColorKey,
    GradeType,
    HeldDayTimesCounter,
    LocationCode,
    PlaceHeldDays,
    PlaceId,
    RaceCourse,
    RaceDateTime,
    RaceDetailFieldKey,
    RaceDetailKvFieldConfig,
    RaceDetailKvSectionConfig,
    RaceDetailLinksSectionConfig,
    RaceDetailPlayersSectionConfig,
    RaceDetailSectionConfig,
    RaceDetailUiConfig,
    RaceId,
    RaceLink,
    RaceNumber,
    RacePlayerId,
    RaceStage,
} from './domain';
export {
    accumulateHeldDayTimes,
    BOATRACE_HCD_CODES,
    buildCalendarEventId,
    buildDefaultRaceDetailConfig,
    buildFetchDateList,
    buildRaceLinks,
    CONDITION_DATA_REQUIRED_ERROR,
    composePlaceId as generatePlaceId,
    composeRaceId as generateRaceId,
    composeRacePlayerId as generateRacePlayerId,
    convertRaceEntityToCalendarEvent,
    createPlaceCodeForNetkeiba,
    createPlaceCodeForOfficial,
    decomposePlaceId as parsePlaceId,
    derivePlaceDateKey,
    extractAutoraceGradeFromText,
    extractAutoraceRaceName,
    extractAutoraceRaceStage,
    extractBoatraceHeadingGrade,
    extractGradeByPatterns,
    extractKeirinGradeFromText,
    extractKeirinRaceGrade,
    extractKeirinRaceName,
    extractKeirinRaceStage,
    extractRaceTypeFromRaceId,
    findPlaceCodeByName,
    findPlaceNameByCode,
    formatLocationForCalendar,
    formatStageForCalendar,
    formatSummaryForCalendar,
    GOOGLE_CALENDAR_ALL_COLORS,
    GoogleCalendarColor,
    GoogleCalendarColorKeyMap,
    GradeMaster,
    GradeTypeSchema,
    getGoogleCalendarColor,
    getPriority,
    isCalendarEventDeleteTarget,
    isHorseRace,
    isIncludedRaceType,
    isMechanicalRace,
    isPlaceWithoutRaceList,
    isSpecifiedRace,
    isYearlyFetchRaceType,
    PLACE_GRADE_REQUIRED_ERROR,
    PlaceHeldDaysSchema,
    PlaceIdSchema,
    processJraRaceName,
    processNarRaceName,
    processOverseasRaceName,
    RACE_DETAIL_FIELD_KEYS,
    RACE_DETAIL_FIELDS,
    RaceCourseSchema,
    RaceDateTimeSchema,
    RaceStageSchema,
    RaceType,
    RaceTypeSchema,
    raceStageRequiredSuperRefine,
    resolveRaceDetailUi,
    StageAliasList,
    StageMap,
    StagePriorityList,
    shouldDisplayCalendarEvent,
    shouldHaveConditionDataForHorse,
    shouldHavePlaceGradeForMechanical,
    shouldIncludeInCalendar,
    UNKNOWN_PLACE_CODE,
    validateGradeType,
    validateLocationCode,
    validatePlaceHeldDays,
    validatePlaceId,
    validateRaceDistance,
    validateRaceId,
    validateRaceName,
    validateRacePlayerId,
    validateRaceSurfaceType,
    validateRaceType,
} from './domain';
// dto
export type {
    CalendarFilterParams,
    CalendarRaceEntity,
    CalendarUpsertResult,
    UpsertApiResponse,
} from './dto';
export { createEmptyCalendarUpsertResult } from './dto/calendarUpsertResult';
// entity
export type {
    CalendarDataEntity,
    CalendarFlagEntity,
    PlaceEntity,
    PlayerEntity,
    RaceEntity,
    RacePlayerEntity,
} from './entity';
export {
    CalendarFlagEntitySchema,
    generatePlaceEntity,
    PlaceEntitySchema,
    RaceEntitySchema,
    RacePlayerEntitySchema,
    validateCalendarDataEntity,
    validateCalendarFlagEntity,
    validatePlaceEntity,
    validatePlayerEntity,
    validateRaceEntity,
    validateRacePlayerEntity,
} from './entity';

// gateway
export type { GithubIssueSummary, IGithubIssueGateway } from './gateway';
export { GithubIssueGateway } from './gateway';

// http
export type {
    InternalErrorResponseBody,
    ParseResult,
    ServiceAuthExemptReason,
    ServiceAuthExemptRoute,
} from './http';
export {
    badRequest,
    bodyLimitMiddleware,
    buildCacheControlHeader,
    buildETagFromContent,
    buildETagFromUpdatedAt,
    FETCH_TIMEOUT_MS,
    fetchWithTimeout,
    getAllowedOrigins,
    internalErrorResponse,
    internalErrorResponseBody,
    isCacheableGetResponse,
    isExempt,
    isNoneMatch,
    json,
    logInternalError,
    parseBodyOrBadRequest,
    parseCommonSearchParams,
    parseOrBadRequest,
    parseQueryParams,
    parseRaceSearchParams,
    REQUEST_ID_HEADER,
    rateLimitMiddleware,
    readServiceAuthToken,
    requireServiceAuth,
    resolveRaceIdOrBadRequest,
    SERVICE_AUTH_HEADER,
    securityHeadersMiddleware,
    shouldRateLimit,
    verifyServiceAuthToken,
    withCorsHeaders,
    withRequestIdHeader,
    withServiceAuthHeader,
} from './http';

// schemas
export type {
    Announcement,
    RaceDetailUi,
    RaceDetailUiConfigInput,
    ReleaseNote,
    ReleaseNoteWrite,
    SearchPlaceFilterParamsInput,
    SearchPlayerFilterParamsInput,
    SearchRaceFilterParamsInput,
} from './schemas';
export {
    announcementSchema,
    calendarUpsertResultSchema,
    formatZodIssues,
    parsePlaceEntityUpsert,
    parsePlayerEntityUpsert,
    parseRaceEntityUpsert,
    playerBaseFieldsSchema,
    raceDetailUiConfigSchema,
    raceDetailUiSchema,
    releaseNoteSchema,
    releaseNoteWriteSchema,
    searchPlaceFilterParamsSchema,
    searchPlayerFilterParamsSchema,
    searchRaceFilterParamsSchema,
    upsertResultSchema,
} from './schemas';

// utilities
export type { CloudFlareEnv, UpsertResult } from './utilities';
export {
    API_REQUIRED_KEYS,
    appLogger,
    chunkArray,
    createAnchorTag,
    createDIInitializer,
    createEmptyUpsertResult,
    createErrorMessage,
    createJstDate,
    createNetkeibaJraRaceVideoUrl,
    createNetkeibaJraShutubaUrl,
    createNetkeibaNarRaceVideoUrl,
    createNetkeibaNarShutubaUrl,
    createNetkeibaRedirectUrl,
    createNetkeirinRaceShutubaUrl,
    createYoutubeLiveUrl,
    EnvStore,
    formatDayDigits,
    formatJstDatetime,
    formatMonthDigits,
    getCurrentUserId,
    getJstDate,
    getJstHours,
    getJstMinutes,
    getJstMonth,
    getJstSeconds,
    getJstYear,
    getRequestId,
    handleControllerError,
    isEnvFlagTrue,
    isInternalServiceCall,
    isProductionEnvironment,
    isValidHtmlString,
    JST_TIMEZONE,
    LogAllMethods,
    MS_PER_DAY,
    mergeUpsertApiResponses,
    normalizeToHalfWidth,
    replaceFromCodePoint,
    requireEnvVar,
    resolveChunkSize,
    resolveInternalErrorMessage,
    resolveRequestId,
    runWithCurrentUserId,
    runWithInternalServiceCall,
    runWithRequestId,
    sanitizeError,
    sleep,
    timingSafeEqualString,
    toErrorMessage,
    toJstISOString,
    toXDigits,
    ValidationError,
} from './utilities';
