#!/usr/bin/env bun
/**
 * build-gap-comment.ts
 *
 * `test-gap-analysis.ts --json` の出力（gap.json）を読み込み、
 * coverage-pr.yml の PR コメント用 Markdown を標準出力に書き出す。
 *
 * 以前は .github/workflows/coverage-pr.yml に `bun -e "..."` を直接埋め込んでいたが、
 * `bun -e` は内部で例外が発生しても静かに握りつぶし、終了コード0・出力なしのまま
 * 処理が止まることがある（gap.json の形状変更時にこれで気づかず PR コメントが
 * 空のまま success 扱いになった）。実ファイルとして実行することで、
 * 壊れた場合は普通に例外が投げられ、ワークフローがちゃんと気づける形にする。
 *
 * 使い方:
 *   bun scripts/build-gap-comment.ts gap.json [--test-failed]
 *
 * `--test-failed` を渡すと、コメント冒頭にテスト失敗を明示する警告バナーを追加する
 * （CICD-06: `bun run test` は内部で `;` 連結された表示用スクリプトが後続するため
 * テスト失敗時も exit code 0 を返す設計になっており、CI のステップ結果だけでは
 * 失敗を検知できない。呼び出し側が生の `bun test` コマンドの終了コードを見て
 * このフラグを渡す）。
 *
 * `--patch-failed` を渡すと、コメント冒頭に変更ファイルのカバレッジ不足を明示する
 * 警告バナーを追加する（check-patch-coverage.ts の判定結果を呼び出し側が渡す）。
 */

import { readFileSync } from 'node:fs';

interface GapFile {
    file: string;
    funcsPct: number;
    linesPct: number;
    uncoveredLines: string;
}

interface PackageGap {
    package: string;
    totalSrcFiles: number;
    coveredSrcFiles: number;
    gapSrcFiles: GapFile[];
}

interface GapReport {
    results: PackageGap[];
    notes: string[];
}

const GAP_FILE_LIST_LIMIT = 50;

const formatGapFile = (gapFile: GapFile): string => {
    const range = gapFile.uncoveredLines ? ` [${gapFile.uncoveredLines}]` : '';
    return `- ${gapFile.file} (Funcs ${gapFile.funcsPct}% / Lines ${gapFile.linesPct}%)${range}`;
};

const buildTableSection = (results: PackageGap[]): string[] => {
    const lines = [
        '| Package | Covered / Total | Coverage Ratio |',
        '|---------|------------------|----------------|',
    ];
    for (const result of results) {
        const ratio =
            result.totalSrcFiles === 0
                ? 100
                : Math.round(
                      (result.coveredSrcFiles / result.totalSrcFiles) * 100,
                  );
        lines.push(
            `| ${result.package} | ${result.coveredSrcFiles} / ${result.totalSrcFiles} | ${ratio}% |`,
        );
    }
    return lines;
};

const buildGapDetailSection = (results: PackageGap[]): string[] => {
    const lines = [
        '<details><summary>100%未満の src ファイル一覧</summary>',
        '',
    ];
    for (const result of results) {
        if (result.gapSrcFiles.length === 0) continue;
        lines.push(`### ${result.package} (${result.gapSrcFiles.length})`);
        for (const gapFile of result.gapSrcFiles.slice(
            0,
            GAP_FILE_LIST_LIMIT,
        )) {
            lines.push(formatGapFile(gapFile));
        }
        if (result.gapSrcFiles.length > GAP_FILE_LIST_LIMIT) {
            lines.push(
                `- ... and ${result.gapSrcFiles.length - GAP_FILE_LIST_LIMIT} more`,
            );
        }
        lines.push('');
    }
    lines.push('</details>');
    return lines;
};

const buildNotesSection = (notes: string[]): string[] => [
    '<details><summary>📝 補足（対応不要な既知の例外パターン）</summary>',
    '',
    ...notes,
    '',
    '</details>',
];

const buildTestFailureBanner = (): string[] => [
    '> ⚠️ **`bun run test` がテスト失敗（非0終了）で完了しました。**',
    '> 以下のカバレッジ集計はテストが実行された範囲の結果であり、失敗したテストの',
    '> 詳細は CI ログを確認してください。この警告が出ている間は gap 表が「緑」に',
    '> 見えてもマージ可能とは限りません。',
    '',
];

const buildPatchFailureBanner = (): string[] => [
    '> 🚫 **このPRで変更したファイルに C0/C1 カバレッジ100%未満のものがあります。**',
    '> 新規/変更したコードには必ずユニットテストを書いてください',
    '> （詳細は下記の「100%未満の src ファイル一覧」、または CI ログを確認）。',
    '> このチェックはブロッキングです。',
    '',
];

const buildComment = (
    report: GapReport,
    testFailed: boolean,
    patchFailed: boolean,
): string => {
    const lines = [
        '## 🧪 Test Gap Report',
        '',
        ...(testFailed ? buildTestFailureBanner() : []),
        ...(patchFailed ? buildPatchFailureBanner() : []),
        ...buildTableSection(report.results),
        '',
        ...buildGapDetailSection(report.results),
        '',
        ...buildNotesSection(report.notes),
        '',
        '_Generated by `scripts/test-gap-analysis.ts`. 詳細は .claude/docs/testing-conventions.md を参照_',
    ];
    return lines.join('\n');
};

const main = (): void => {
    const gapJsonPath = process.argv[2];
    if (!gapJsonPath) {
        throw new Error(
            '使い方: bun scripts/build-gap-comment.ts <gap.jsonのパス> [--test-failed] [--patch-failed]',
        );
    }
    const testFailed = process.argv.includes('--test-failed');
    const patchFailed = process.argv.includes('--patch-failed');
    const report = JSON.parse(readFileSync(gapJsonPath, 'utf8')) as GapReport;
    process.stdout.write(`${buildComment(report, testFailed, patchFailed)}\n`);
};

main();
